### ISSUE TITLE
some questions about the vec_ids 

### ISSUE THREAD

**Issue by zhhao1** [kamperh/eskmeans#2]
Thaks very much.  Your logic is clear, and the method is beautiful. After reading the code in recipe_zs2017_track2-master, i have a better understand. But i still have some questions.
Fisrt, you give an example with landmarks = [1, 2, 3]. In my understanding, it means that the whole utterance have three frames and every position can be a word boundary. Is 3 represent the end of the utterance?
Second, if landmarks = [1, 2, 3] and n_landmarks_max = 20 , the vec_ids will be [embed[0:1], embed[0:2], embed[1:2], embed[0:3], embed[1:3], embed[2:3] ].
But when downsampling, the order of seglist to be used, which is defined in recipe_zs2017_track2master/downsample/get_seglist.py may be [embed[0:1], embed[0:2], embed[0:3], embed[1:2], embed[1:3], embed[2:3] ].
I don’t know where I got it wrong, and I hope you can point it out. Sorry for taking your time.
![捕获](https://user-images.githubusercontent.com/46468492/88195466-abddcf80-cc72-11ea-80b3-36899a64ca7a.PNG)

**Comment by kamperh** [comment]
Hey @7zhanghao,

Wow, you are going through the code in great detail; really appreciate that!  I had to do quite a bit of digging since you rightly point out a mismatch between the code extracting the embeddings and the `vec_ids`.

The code which changes the embeddings from the order obtained in `get_seglist_from_landmarks` to the order expected for `vec_ids` is given here:

https://github.com/kamperh/recipe_zs2017_track2/blob/7d3809b94429cbb0999f1c8f26932c43d016a06c/segmentation/get_data_downsample.py#L54-L76

To see how this works, just have a look at this sample snippet (based on the code in the link above):
```
i_embed = 0 
for cur_start in range(n_slices): 
    for cur_end in range(cur_start, min(n_slices, cur_start + n_landmarks_max)): 
        cur_end += 1 
        t = cur_end 
        i = int(t*(t - 1)/2) 
        print("position in vec_ids: {}; position in seglist: {}".format(i + cur_start, i_embed)) 
        i_embed += 1 
```
which gives output:
```
position in vec_ids: 0; position in seglist: 0
position in vec_ids: 1; position in seglist: 1
position in vec_ids: 3; position in seglist: 2
position in vec_ids: 2; position in seglist: 3
position in vec_ids: 4; position in seglist: 4
position in vec_ids: 5; position in seglist: 5
```
showing how the positions are changed.  Hope that helps!  Let me know if that answers the question and I'll close the issue.

**Comment by 7zhanghao** [comment]
It really helps and i understand. Thank you very much. And sorry for taking your time again.

**Comment by zhhao1** [comment]
> Hey @7zhanghao,
> 
> Wow, you are going through the code in great detail; really appreciate that! I had to do quite a bit of digging since you rightly point out a mismatch between the code extracting the embeddings and the `vec_ids`.
> 
> The code which changes the embeddings from the order obtained in `get_seglist_from_landmarks` to the order expected for `vec_ids` is given here:
> 
> https://github.com/kamperh/recipe_zs2017_track2/blob/7d3809b94429cbb0999f1c8f26932c43d016a06c/segmentation/get_data_downsample.py#L54-L76
> 
> To see how this works, just have a look at this sample snippet (based on the code in the link above):
> 
> ```
> i_embed = 0 
> for cur_start in range(n_slices): 
>     for cur_end in range(cur_start, min(n_slices, cur_start + n_landmarks_max)): 
>         cur_end += 1 
>         t = cur_end 
>         i = int(t*(t - 1)/2) 
>         print("position in vec_ids: {}; position in seglist: {}".format(i + cur_start, i_embed)) 
>         i_embed += 1 
> ```
> 
> which gives output:
> 
> ```
> position in vec_ids: 0; position in seglist: 0
> position in vec_ids: 1; position in seglist: 1
> position in vec_ids: 3; position in seglist: 2
> position in vec_ids: 2; position in seglist: 3
> position in vec_ids: 4; position in seglist: 4
> position in vec_ids: 5; position in seglist: 5
> ```
> 
> showing how the positions are changed. Hope that helps! Let me know if that answers the question and I'll close the issue.

It really helps and i understand. Thank you very much. And sorry for taking your time again.

**Comment by kamperh** [comment]
Big pleasure and no problem at all!  It's good to see someone checking the code, and hopefully it helps you!
